# Generated by Django 2.1.2 on 2018-11-30 12:34

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='文章标题')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创作时间')),
                ('pic', models.ImageField(upload_to='pics', verbose_name='文章配图')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('count', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name_plural': '文章表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('content', models.CharField(max_length=140, verbose_name='回复内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='评论文章')),
            ],
            options={
                'verbose_name_plural': '评论表',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name_plural': '文章分类表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=10, verbose_name='昵称')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='头像')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('desc', models.CharField(max_length=140, verbose_name='个人简介')),
                ('date', models.DateField(auto_now_add=True, verbose_name='注册日期')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='blog.Comment', verbose_name='被评论用户'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='文章作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Type', verbose_name='文章分类'),
        ),
    ]
