# Generated by Django 2.1.7 on 2019-05-12 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('8ff6b192-0e47-496a-aad1-922eb65749a5'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('7d8937eb-083c-4ef0-bfba-46d988d47470'), max_length=128, verbose_name='唯一标识符'),
        ),
    ]
