# Generated by Django 2.1.7 on 2019-05-12 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190512_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('41ec1bac-5b16-4659-b58f-20e775c8660f'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('b3923342-a60a-4e93-92c7-df22977a8910'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
