# Generated by Django 2.1.7 on 2019-05-12 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190512_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('31e9de6a-edd0-4e96-9ecf-4c2f626486da'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('75ed2cf4-5d0b-4c29-a3f9-b669123dd041'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
