# Generated by Django 2.1.7 on 2019-05-12 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190512_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('392e8db4-fcd2-4bb9-878c-6f66c56530ce'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('e8d433eb-404d-4673-9718-6d2def2edb1f'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
