# Generated by Django 2.1.7 on 2019-05-13 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190512_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('a69583aa-6c81-43d0-8cf9-1faece54a050'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('315383b5-8ea7-40d8-a429-45c5913ebafe'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
