# Generated by Django 2.1.7 on 2019-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190513_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default='leavemsg_uuid=396d852f-272e-47f4-93ac-1d05b97f05f5', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='user_uuid=f099d45a-7e23-4994-9abd-a140e2933973', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
