# Generated by Django 2.1.7 on 2019-05-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190513_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default='leavemsg_uuid=c1d06ebe-bb2b-4436-a9f2-ca29b505698b', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='user_uuid=b42143d2-02ed-4fea-b134-ccfea1329225', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
