# Generated by Django 2.1.7 on 2019-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190513_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default='leavemsg_uuid=072e025d-02fc-448f-9a01-5aff156d4d71', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='user_uuid=64b998d1-b03b-406c-9941-39f18a2dc15d', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
