# Generated by Django 2.1.7 on 2019-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190513_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default='leavemsg_uuid=JK3kppWG8WYXoTSKQKbTB8', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='user_uuid=jzAdxZ868bt2gEKYEZcn2C', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
