# Generated by Django 2.1.7 on 2019-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190513_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default='reward_uuid=guNU8t8i', max_length=36, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='reward_uuid=qLfcSXgK', max_length=36, unique=True, verbose_name='唯一标识符'),
        ),
    ]
