# Generated by Django 2.1.7 on 2019-05-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190513_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='unique_id',
            field=models.CharField(default='88zw0khm', max_length=36, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='13hnfu55', max_length=36, unique=True, verbose_name='唯一标识符'),
        ),
    ]
