# Generated by Django 2.1 on 2019-04-23 16:59

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='文章标题')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='blog/pics', verbose_name='文章配图')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='文章简介')),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_plant', models.IntegerField(default=0, verbose_name='是否轮播')),
                ('is_top', models.IntegerField(default=0, verbose_name='是否置顶')),
                ('is_recommend', models.IntegerField(default=0, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
            },
        ),
        migrations.CreateModel(
            name='Articlecol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '文章收藏表',
                'verbose_name_plural': '文章收藏表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='回复内容')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='评论文章')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=True, to='blog.Comment', verbose_name='被评论用户')),
            ],
            options={
                'verbose_name': '文章评论表',
                'verbose_name_plural': '文章评论表',
            },
        ),
        migrations.CreateModel(
            name='JsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('lifetime', models.DateTimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20, unique=True, verbose_name='标签名称')),
                ('label', models.CharField(max_length=255, verbose_name='标签简介')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章标签表',
                'verbose_name_plural': '文章标签表',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20, unique=True, verbose_name='分类名称')),
                ('label', models.CharField(max_length=255, verbose_name='分类简介')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章分类表',
                'verbose_name_plural': '文章分类表',
            },
        ),
        migrations.CreateModel(
            name='WxToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('lifetime', models.DateTimeField(default=0)),
            ],
        ),
    ]
