# Generated by Django 2.1.7 on 2019-04-26 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
