# Generated by Django 2.1.7 on 2019-05-12 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('ee480fdb-fe0b-4650-8148-027cc22667f3'), max_length=128, verbose_name='唯一标识符'),
        ),
    ]
