# Generated by Django 2.1.7 on 2019-05-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_type_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default='', max_length=128, verbose_name='唯一标识符'),
        ),
    ]
