# Generated by Django 2.1.7 on 2019-05-12 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190512_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('7449d55b-0e3e-45c1-aff1-5620e4a06ce7'), max_length=128, verbose_name='唯一标识符'),
        ),
    ]
