# Generated by Django 2.1.7 on 2019-05-12 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190512_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('036591cc-5c8d-4a6e-afb1-99f65e2b647a'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AddField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('58f255e5-ea37-4418-88ff-28bdf2946c4b'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AddField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('9c6c68d7-88d2-4257-81f0-04bb8e321bd6'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AddField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('124ec791-8df0-4810-850e-5bd131222a03'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AddField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('d247d02e-fe77-45b3-ac0a-606392b91606'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('cd0e16c0-36ce-4670-a9ea-8882b8766aa6'), max_length=128, verbose_name='唯一标识符'),
        ),
    ]
