# Generated by Django 2.1.7 on 2019-05-12 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190512_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('4eae8ac8-c8ca-48e1-994a-290c857d27c3'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('7e2e2dca-13a6-41c8-8896-7a0d78d8f339'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('20bd906b-b4ad-4ef7-a0c9-0d3c0d11c791'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('e83b03cc-0fb1-4c84-9ae5-b92272e429b1'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('2ebdbb9b-2eb8-443a-9f7c-5df376f5d10c'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('b94514b0-1e8b-428d-99ba-00108265bf0e'), max_length=128, verbose_name='唯一标识符'),
        ),
    ]
