# Generated by Django 2.1.7 on 2019-05-12 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190512_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('8d2f31c1-8130-4a81-a14b-d9d9d83c46ab'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('a696227b-3156-43d3-a787-6e1a22de2b05'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('9859143a-29f9-485c-a7cc-39d05def5f8a'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('ada94e8f-1026-4a8a-95d4-7d3f5fa7c335'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('6793f4ab-7f76-4fb2-979b-5d3d8c6fa117'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('d105a5d9-9d0f-4b3b-8d4d-a56d05e92e59'), max_length=128, verbose_name='唯一标识符'),
        ),
    ]
