# Generated by Django 2.1.7 on 2019-05-12 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190512_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('bd4d54c1-25a6-493c-903f-16364d57791a'), max_length=128, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('f364dd10-ce9e-4f12-bcd9-2e9ab6e75fa0'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('19954a00-71f9-45a9-9a59-9702ac946409'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('cdb99750-a37b-416a-87aa-5262ca4dcef5'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('18366817-e026-444b-b5b0-e292cd7f2e47'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('fcff2284-8859-46e1-8d25-3f752ad21ea1'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
