# Generated by Django 2.1.7 on 2019-05-12 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190512_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('634b7a49-39d2-46af-9fc6-ce3cdb176310'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('f937a4d9-a980-48f9-8f47-12a1198c82d6'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('74f932b0-1e04-44b3-9858-11e165ddf505'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('e97dcacf-f59b-49de-8cb0-695fded6fe18'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('a49886d5-f7d4-431b-9811-929a20585dfa'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('1a2a21d9-c4bd-48b2-94b9-b417fda43878'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
