# Generated by Django 2.1.7 on 2019-05-12 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190512_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('89a45af8-4bfc-4c13-ba11-b6f7ef0ce252'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('d29b8b7b-c204-4842-b3ff-77a2d27162b9'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('051959a6-4917-47d0-ae1d-e9a493f3a98d'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('d56d44be-92ca-4150-b857-b3b838a7858e'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('06ed60d9-90a5-4fdf-a4fa-b13dbc9ab8fc'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('b5dc688b-df9e-4140-9adb-6ce727a87704'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
