# Generated by Django 2.1.7 on 2019-05-13 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190512_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('6d9f9c25-4d0a-4386-812e-c8da269df51a'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('50210ad3-64fc-444c-84e0-ded76725c0dc'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('7b4be8ec-fda8-4eb9-88ce-76812116d260'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('255eed30-06c1-4feb-aeea-dad457728f61'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('ae28610d-a083-4a03-a9db-56207cc6233b'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default='type_uid=6fd95c07-e95d-4c32-8c77-99ccab139782', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
