# Generated by Django 2.1.7 on 2019-05-13 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190513_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('dec364b0-ae38-462c-bacd-a395870ead80'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('97a65b13-66d9-4454-8f35-fc42aeb158c2'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('b2bad13e-02a6-4fd9-986c-fce08aa7ed8e'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('cd72895a-550e-41d4-9e0f-e57dacff7db0'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('0b63ecac-0fdf-4be7-8777-edc37588a45c'), max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default='type_uuid=03a13896-3244-4c77-83ec-a5462bc802e5', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
