# Generated by Django 2.1.7 on 2019-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190513_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default='article_uuid=1e6e47a2-994e-4a8f-a43f-667f64e26c3d', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default='articlecol_uuid=69c3be63-2dca-45b9-beac-4029a778331d', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default='comment_uuid=694878a4-e2d1-43e4-82d5-bc0f432348a6', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default='reward_uuid=538b3f0d-c5d9-465a-9903-33ad3b67cfab', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default='tag_uuid=4fd36662-59d3-4faa-89ec-1e026c9f6cf0', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default='type_uuid=4dd28cbf-3ab5-4db8-8c49-5cce9fbf3b94', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
