# Generated by Django 2.1.7 on 2019-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190513_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(default='article_uuid=BbpGrvEVgiPruEkERdjhR2', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='articlecol',
            name='unique_id',
            field=models.CharField(default='articlecol_uuid=XBBcveAYNH2mAxMRry8U3R', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(default='comment_uuid=MeFoyXvny7it6qb2Dni76h', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(default='reward_uuid=gKw4cXXMu5XbwZsnAfHuV4', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_id',
            field=models.CharField(default='tag_uuid=jvi7JVHyRCy3RS4gG7tcb9', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unique_id',
            field=models.CharField(default='type_uuid=PfsSNoVzwH6JxeTbcnrSgh', max_length=128, unique=True, verbose_name='唯一标识符'),
        ),
    ]
